Add dropdowns
hackoregon/housing-frontend pull request #25
Opened 2017-04-27 04:17 UTC by dsdemaria

From issue #18 – Implements the Dropdown component from the component library (bells and whistles included).

2017-04-28 00:41 UTC, JohnTasto commented
From Travis CI:

```
/home/travis/build/hackoregon/housing-frontend/src/client.js (2/0)
  ✖  2:1  Unexpected '!' in '!style-loader!css-loader!@hackoregon/component-library/assets/leaflet.css'. Do not use import syntax to configure webpack loaders  import/no-webpack-loader-syntax
  ✖  2:8  Unable to resolve path to module '!style-loader!css-loader!@hackoregon/component-library/assets/leaflet.css'                                          import/no-unresolved
/home/travis/build/hackoregon/housing-frontend/src/components/App/index.js (1/0)
  ✖  79:1  Line 79 exceeds the maximum line length of 100  max-len
✖ 3 errors (4:36:38 AM)
```

2017-04-28 02:26 UTC, JohnTasto commented
This is the correct error:
```
$ yarn
yarn install v0.23.2
error An unexpected error occurred: "Unknown token 4832:1 in /home/travis/build/hackoregon/housing-frontend/yarn.lock".
info If you think this is a bug, please open a bug report with the information provided in "/home/travis/build/hackoregon/housing-frontend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

There is still an unresolved merge conflict in yarn.lock on line 4832:
```
<<<<<<< HEAD
react-input-autosize@^1.1.0:
  version "1.1.0"
  resolved "https://registry.yarnpkg.com/react-input-autosize/-/react-input-autosize-1.1.0.tgz#3fe1ac832387d8abab85f6051ceab1c9e5570853"

react-leaflet@^1.1.4:
=======
react-leaflet@^1.1.4, react-leaflet@^1.1.6:
>>>>>>> upstream/master
```

2017-04-30 16:57 UTC, nmuldavin requested changes
Can you bring this up to date with recent changes, either by copying over to a new branch or rebasing? I left a few comments

2017-04-30 16:57 UTC, nmuldavin commented on src/state/parameters/reducer.js
> +        },
Why doesn't 

```
unitSize: action.payload
```

work here?

2017-04-30 16:57 UTC, nmuldavin commented on package.json
> +    "@hackoregon/component-library": "^0.2.0",
When you resubmit this should be up to date already

2017-04-30 16:57 UTC, nmuldavin commented on src/components/App/index.js
> +      />
After #39 there will be just one dropdown for both . . . not sure how they'll be arranged but we'll figure that out later.

2017-05-01 14:48 UTC, closed without merging