Add demographics detail view
hackoregon/housing-frontend pull request #34
Opened 2017-04-29 08:11 UTC by JohnTasto

`src/state/households` and `src/state/populations` are basically simplified versions of `src/state/affordability` and `src/state/rent` - simplified in that the API doesn't take any url parameters. `fetchHouseholdData` and `fetchPopulationsData` are both dispatched only once when `<App />` mounts.

A `neighborhood` property is also added to the `parameters` state to keep track of which neighborhood is selected. Maybe it should be named something else or moved out of `parameters`, but I felt it was a good fit.

Finally, `<DemographicsDetailView />` could probably be broken up into subcomponents, but whatever. It could also use some more styling.

<img width="1200" alt="screen shot 2017-04-29 at 12 47 05 am" src="https://cloud.githubusercontent.com/assets/5026892/25553982/e9ff2452-2c76-11e7-98d0-ec5c8359567c.png">

2017-04-29 22:55 UTC, DingoEatingFuzz commented
Things we still want to do (not blocking merging):

  - Denote which neighborhood is selected
  - Style the "tooltip" so it's the association with the map is clearer
  - Comma-format large numbers.

2017-04-29 23:04 UTC, JohnTasto commented
@nmuldavin removed the popup tooltip in #31 - I figured we could draw a thicker outline around the selected neighborhood or something.

2017-04-29 23:05 UTC, nmuldavin commented
The wireframe has a pink outline around the selected neighborhood, I think that would look nice

2017-04-29 23:14 UTC, nmuldavin commented
Just pulled this up on my machine. I know there was talk about not needing the detail view but so glad you did this work, I think it really rounds it out. Thanks @JohnTasto!

2017-04-29 23:47 UTC, DingoEatingFuzz requested changes
Just the one change we talked about in person, this it's good to 🚢 !

2017-04-29 23:47 UTC, DingoEatingFuzz commented on src/utils/data-constants.js
> +];
We should get the name from the data provided to the map instead of re-associating it by means of this constant.

2017-04-30 01:14 UTC, JohnTasto commented on src/utils/data-constants.js
> +];
Done!

2017-04-30 03:26 UTC, DingoEatingFuzz approved these changes

2017-04-30 06:38 UTC, merged